config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    post "/homes" => "homes#creat"
    get "/about" => "homes#about"

    resources :homes, only: [:top, :about]
    # 食事メニュー表
    resources :cooking_menu_lists, only: [:index, :create,]
    # 美容、栄養豆知識表
    resources :beauty_nutrition_knowledges, only: [:index, :create,]
    # 会員
    get   "/customers/my_page" => "customers#show"
    get   "/customers/edit_page" => "customers#edit"
    patch "/customers/infomation" => "customers#update"
    get   "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    get   "/customers/guest" => "customers#index"

    # 体調管理記録表
    resources :health_records, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 活動、睡眠記録表
    resources :activity_and_sleep_log_charts, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 服用記録表
    resources :dosage_record_sheets


    # 処方箋一覧
    resources :prescription_lists, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 次回受診日表
    resources :next_medical_checkup_date_lists, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :create, :edit, :update, :destroy]
    # 管理者　美容、栄養豆知識表
    resources :beauty_nutrition_knowledges do
  end
    # 管理者　食事メニュー表
    resources :cooking_menu_lists, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/beauty_nutrition_knowledge.rb
# frozen_string_literal: true

class BeautyNutritionKnowledge < ApplicationRecord
  # 美容、栄養豆知識表
  enum genre: { beauty: 0, nutrition: 1 }
  validates :title, presence: true
  validates :content, presence: true
  validates :genre, inclusion: { in: BeautyNutritionKnowledge.genres.keys }
end

# == Schema Information
#
# Table name: beauty_nutrition_knowledges
#
#  id         :integer          not null, primary key
#  content    :text
#  genre      :integer          not null
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/admin/beauty_nutrition_knowledge_controller.rb
class Admin::BeautyNutritionKnowledgeController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/beauty_nutrition_knowledges_controller.rb
# frozen_string_literal: true

#美容,栄養の豆知識
class Admin::BeautyNutritionKnowledgesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @beauty_nutrition_knowledges = BeautyNutritionKnowledge.all
  end

  def new
    @beauty_nutrition_knowledge = BeautyNutritionKnowledge.new
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @beauty_nutrition_knowledge = BeautyNutritionKnowledge.new(beauty_nutrition_knowledge_params)

    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @beauty_nutrition_knowledge.save
      flash[:notice] = "success"
      # 4. 詳細画面へリダイレクト
      redirect_to admin_beauty_nutrition_knowledges_path
    else
      flash.now[:alert] = "failed"
      render :new
    end
  end

  def show
    @beauty_nutrition_knowledge = BeautyNutritionKnowledge.find(params[:id])
  end

  def edit
    @beauty_nutrition_knowledge = BeautyNutritionKnowledge.find(params[:id])
  end

  def update
    beauty_nutrition_knowledge = BeautyNutritionKnowledge.find(params[:id])
    beauty_nutrition_knowledge.update(beauty_nutrition_knowledge_params)
    redirect_to admin_beauty_nutrition_knowledges_path(beauty_nutrition_knowledge.id)
  end

  def destroy
    beauty_nutrition_knowledge = BeautyNutritionKnowledge.find(params[:id])  # データ（レコード）を1件取得
    beauty_nutrition_knowledge.destroy  # データ（レコード）を削除
    redirect_to admin_beauty_nutrition_knowledges_path  # 投稿一覧画面へリダイレクト
  end


  private
    # ストロングパラメータ
    def beauty_nutrition_knowledge_params
      params.require(:beauty_nutrition_knowledge).permit(:title, :genre, :content)
    end
end

app/helpers/admin/beauty_nutrition_knowledge_helper.rb
# frozen_string_literal: true

module Admin::BeautyNutritionKnowledgeHelper
end

app/views/admin/beauty_nutrition_knowledges/_form.html.erb
<%= form_with model: [:admin, beauty_nutrition_knowledge], local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <%= f.text_field :title %>

  <h4>ジャンル名</h4>
      <%= f.select :genre, BeautyNutritionKnowledge.genres.map {|k, v| [t("enums.beauty_nutrition_knowledge.genre.#{k}"), k ]},
                                                                    { selected: beauty_nutrition_knowledge.genre, include_blank: "選択してください" },
                                                                    { class: "form-controle" } %>

  <h4>内容</h4>
     <%= f.text_area :content %>

     <%= f.submit message %>
<% end %>

app/views/admin/beauty_nutrition_knowledges/edit.html.erb
<h2>美容栄養豆知識 編集画面</h2>

<%= render 'admin/beauty_nutrition_knowledges/form', beauty_nutrition_knowledge: @beauty_nutrition_knowledge, message: "編集する" %>

app/views/admin/beauty_nutrition_knowledges/index.html.erb
<h2>美容栄養豆知識</h2>

<% @beauty_nutrition_knowledges.each do |beauty_nutrition_knowledge| %>

  <p>ジャンル名</p>
  <span><%= link_to beauty_nutrition_knowledge.genre_i18n,  admin_beauty_nutrition_knowledge_path(beauty_nutrition_knowledge) %></span>

   <p>タイトル</p>
  <span><%= link_to beauty_nutrition_knowledge.title,  admin_beauty_nutrition_knowledge_path(beauty_nutrition_knowledge.id) %></span>

   <p>内容</p>
  <span><%= link_to beauty_nutrition_knowledge.content,  admin_beauty_nutrition_knowledge_path(beauty_nutrition_knowledge.id) %></span>

<% end %>

<h4><%= link_to '美容、栄養　豆知識 投稿へ戻る', new_admin_beauty_nutrition_knowledge_path %></h4>

app/views/admin/beauty_nutrition_knowledges/new.html.erb
<h2>美容栄養豆知識</h2>

<%= render 'admin/beauty_nutrition_knowledges/form', beauty_nutrition_knowledge: @beauty_nutrition_knowledge, message: "投稿" %>
<h4><%= link_to '美容、栄養　豆知識 一覧表へ', admin_beauty_nutrition_knowledges_path %></h4>

app/views/admin/beauty_nutrition_knowledges/show.html.erb
<h2>美容栄養豆知識 詳細画面</h2>


  <p>ジャンル名</p>
  <span><%= @beauty_nutrition_knowledge.genre_i18n %></span>

   <p>タイトル</p>
  <span><%= @beauty_nutrition_knowledge.title %></span>

   <p>内容</p>
  <span><%= @beauty_nutrition_knowledge.content %></span>

  <%= link_to "編集",  edit_admin_beauty_nutrition_knowledge_path(@beauty_nutrition_knowledge.id) %>
  <%= link_to "削除",  admin_beauty_nutrition_knowledge_path(@beauty_nutrition_knowledge.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>