config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    post "/homes" => "homes#creat"
    get "/about" => "homes#about"

    resources :homes, only: [:top, :about]
    # 食事メニュー表
    resources :cooking_menu_lists, only: [:index, :create,]
    # 美容、栄養豆知識表
    resources :beauty_nutrition_knowledges, only: [:index, :create,]
    # 会員
    get   "/customers/my_page" => "customers#show"
    get   "/customers/edit_page" => "customers#edit"
    patch "/customers/infomation" => "customers#update"
    get   "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    get   "/customers/guest" => "customers#index"

    # 体調管理記録表
    resources :health_records, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 活動、睡眠記録表
    resources :activity_and_sleep_log_charts, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 服用記録表
    resources :dosage_record_sheets


    # 処方箋一覧
    resources :prescription_lists, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 次回受診日表
    resources :next_medical_checkup_date_lists, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :create, :edit, :update, :destroy]
    # 管理者　美容、栄養豆知識表
    resources :beauty_nutrition_knowledges do
  end
    # 管理者　食事メニュー表
    resources :cooking_menu_lists, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  # 会員
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :email, presence: true

  # 1:Nの関係性　アソシエーション（関連付け）
  has_many :health_records, dependent: :destroy
  has_many :dosage_record_sheets, dependent: :destroy
  has_many :activity_and_sleep_log_charts, dependent: :destroy
  has_many :next_medical_checkup_date_lists, dependent: :destroy
  has_many :prescription_lists, dependent: :destroy




  # 退会ユーザーはログインできなくする
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

# == Schema Information
#
# Table name: customers
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  first_name_kana        :string
#  guest                  :string
#  is_deleted             :boolean          default(FALSE)
#  last_name              :string
#  last_name_kana         :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_customers_on_email                 (email) UNIQUE
#  index_customers_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/admin/customers_controller.rb
# frozen_string_literal: true

#会員一覧画面（管理者用）
class Admin::CustomersController < ApplicationController
  #adminでログインしているのかをチェックしている　管理者以外は閲覧できないようにするもの
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def new
  end

  def create
    # データを受け取り新規登録するためのインスタンス作成
    @customer = Customer.new(customer_params)
    # データをデータベースに保存するためのsaveメソッド実行
    customer.save
    # リダイレクト
    redirect_to admin_customers_path
  end

  def show
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path, notice:"ユーザー情報更新しました"
  end

  def withdraw
    @customer = Customer.find_by(name: params[:name])
    @customer.update(is_valid: false)
    reset_session
    redirect_to root_path
  end

  def destroy
    customer = Customer.find(params[:id])  # データ（レコード）を1件取得
    customer.destroy  # データ（レコード）を削除
    redirect_to admin_customers_path  # 投稿一覧画面へリダイレクト
  end

  private
    def customer_params
      params.require(:customer).permit(:guest, :last_name, :first_name, :email)
    end
end

app/helpers/admin/customers_helper.rb
# frozen_string_literal: true

module Admin::CustomersHelper
end

app/views/admin/customers/create.html.erb
<h1>Admin::Customers#create</h1>
<p>Find me in app/views/admin/customers/create.html.erb</p>

app/views/admin/customers/edit.html.erb
<h2>会員情報編集</h2>
<%= form_with model: [:admin, @customer] do |f| %>

  <h4>メールアドレス</h4>
  <%= f.email_field :email %>


  <%= f.submit '編集' %>

<% end %>

app/views/admin/customers/index.html.erb
<h2>会員一覧</h2>
   <% @customers.each do |customer| %>
     <ul class="list-group">
        <li class="list-group-item">会員ID <span><%= customer.id%></span></li>
        <li class="list-group-item">メールアドレス<span><%= customer.email%></span></li>
        <li class="list-group-item">会員ステータス
                                      <% if customer.is_deleted %>
                                   <p>退会</p>
                                      <% else %>
                                   <p>有効</p>
                                      <% end %></li>
        <h4><%= link_to "編集" , edit_admin_customer_path(id:customer.id) %></h4>
        <h4><%= link_to "削除" , admin_customer_path(id:customer.id), method: :delete, data: { confirm: '本当に削除しますか?' } %></h4>

     </ul>


   <% end %>

app/views/admin/customers/new.html.erb
<h1>Admin::Customers#new</h1>
<p>Find me in app/views/admin/customers/new.html.erb</p>

app/views/admin/customers/show.html.erb
<h1>Admin::Customers#show</h1>
<p>Find me in app/views/admin/customers/show.html.erb</p>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>