config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    post "/homes" => "homes#creat"
    get "/about" => "homes#about"

    resources :homes, only: [:top, :about]
    # 食事メニュー表
    resources :cooking_menu_lists, only: [:index, :create,]
    # 美容、栄養豆知識表
    resources :beauty_nutrition_knowledges, only: [:index, :create,]
    # 会員
    get   "/customers/my_page" => "customers#show"
    get   "/customers/edit_page" => "customers#edit"
    patch "/customers/infomation" => "customers#update"
    get   "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    get   "/customers/guest" => "customers#index"

    # 体調管理記録表
    resources :health_records, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 活動、睡眠記録表
    resources :activity_and_sleep_log_charts, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 服用記録表
    resources :dosage_record_sheets


    # 処方箋一覧
    resources :prescription_lists, only: [:index, :new, :create, :edit, :update, :destroy] do
    end

    # 次回受診日表
    resources :next_medical_checkup_date_lists, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 生成したコントローラがどこに存在するのかを記述
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :create, :edit, :update, :destroy]
    # 管理者　美容、栄養豆知識表
    resources :beauty_nutrition_knowledges do
  end
    # 管理者　食事メニュー表
    resources :cooking_menu_lists, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/cooking_menu_list.rb
# frozen_string_literal: true

class CookingMenuList < ApplicationRecord
  # 食事メニュー表
  validates :title, presence: true
  validates :way_of_making, presence: true
  validates :material, presence: true
  validates :for_how_meny_people, presence: true
end

# == Schema Information
#
# Table name: cooking_menu_lists
#
#  id                  :integer          not null, primary key
#  for_how_meny_people :string
#  material            :text
#  title               :string
#  way_of_making       :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

app/controllers/admin/cooking_menu_list_controller.rb
class Admin::CookingMenuListController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/cooking_menu_lists_controller.rb
# frozen_string_literal: true

#食事メニュー
class Admin::CookingMenuListsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @cooking_menu_list = CookingMenuList.all
  end

  def new
    @cooking_menu_list = CookingMenuList.new
  end

  def create
    # データを受け取り新規登録するためのインスタンス作成
    @cooking_menu_list = CookingMenuList.new(cooking_menu_list_params)
    # データをデータベースに保存するためのsaveメソッド実行
    if @cooking_menu_list.save
      flash[:notice] = "success"
      redirect_to admin_cooking_menu_lists_path
    else
      flash.now[:alert] = "failed"
      render :new
    end
  end

  def show
    @cooking_menu_list = CookingMenuList.find(params[:id])
  end

  def edit
    @cooking_menu_list = CookingMenuList.find(params[:id])
  end

  def update
    cooking_menu_list = CookingMenuList.find(params[:id])
    cooking_menu_list.update(cooking_menu_list_params)
    redirect_to admin_cooking_menu_list_path(admin_cooking_menu_list.id)
  end

  def destroy
    cooking_menu_list = CookingMenuList.find(params[:id])  # データ（レコード）を1件取得
    cooking_menu_list.destroy  # データ（レコード）を削除
    redirect_to "/admin/cooking_menu_lists"  # 投稿一覧画面へリダイレクト
  end

  private
    # ストロングパラメータ
    def cooking_menu_list_params
      params.require(:cooking_menu_list).permit(:title, :for_how_meny_people, :material, :way_of_making)
    end
end

app/helpers/admin/cooking_menu_list_helper.rb
# frozen_string_literal: true

module Admin::CookingMenuListHelper
end

app/views/admin/cooking_menu_lists/edit.html.erb
<h2>食事メニュー　編集画面</h2>

<%= form_with model: @cooking_menu_list, url: '/admin/cooking_menu_lists', method: :post  do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>何人前？</h4>
  <%= f.text_field :for_how_meny_people %>人前

  <h4>材料</h4>
  <%= f.text_field :material %>

  <h4>作り方</h4>
  <%= f.text_area :way_of_making %>

  <%= f.submit '保存' %>
<% end %>

app/views/admin/cooking_menu_lists/index.html.erb
<h2>食事メニューの一覧</h2>

<% @cooking_menu_list.each do |cooking_menu_list| %>

  <p>タイトル</p>
  <span><%= link_to cooking_menu_list.title, admin_cooking_menu_list_path(cooking_menu_list) %></span>

   <p>何人前</p>
  <span><%= link_to cooking_menu_list.for_how_meny_people, admin_cooking_menu_list_path(cooking_menu_list) %></span>

   <p>材料</p>
  <span><%= link_to cooking_menu_list.material, admin_cooking_menu_list_path(cooking_menu_list) %></span>

   <p>作り方</p>
  <span><%= link_to cooking_menu_list.way_of_making, admin_cooking_menu_list_path(cooking_menu_list) %></span>


<% end %>
<h4><%= link_to '食事メニュー　投稿画面へ戻る', new_admin_cooking_menu_list_path %></h4>

app/views/admin/cooking_menu_lists/new.html.erb
<h2>食事メニュー新規投稿</h2>

<%= form_with model: @cooking_menu_list, url: '/admin/cooking_menu_lists', method: :post  do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>何人前？</h4>
  <%= f.text_field :for_how_meny_people %>人前

  <h4>材料</h4>
  <%= f.text_field :material %>

  <h4>作り方</h4>
  <%= f.text_area :way_of_making %>

  <%= f.submit '投稿' %>
<% end %>
<h4><%= link_to '食事メニュー　一覧', admin_cooking_menu_lists_path %></h4>

app/views/admin/cooking_menu_lists/show.html.erb
<h2>食事メニュー詳細画面</h2>


<h4>タイトル</h4>
<p><%= @cooking_menu_list.title %></p>

<h4>何人前</h4>
<p><%= @cooking_menu_list.for_how_meny_people %></p>

<h4>材料</h4>
<p><%= @cooking_menu_list.material %></p>

<h4>作り方</h4>
<p><%= @cooking_menu_list.way_of_making %></p>


<%= link_to "編集", edit_admin_cooking_menu_list_path(@cooking_menu_list.id) %>
<%= link_to "削除", admin_cooking_menu_list_path(@cooking_menu_list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>